# This file was generated by GoReleaser. DO NOT EDIT.
class Tldr < Formula
  desc "Simplified and community-driven man pages (tldr-pages)."
  homepage "https://4d63.com/tldr"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leighmcculloch/tldr/releases/download/v1.1.1/tldr_1.1.1_macos_x64.tar.gz"
    sha256 "245faa2aa2584c6df8e3ec8cd5cf653a013fa11ac87795f1a100d3a08e72e438"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/leighmcculloch/tldr/releases/download/v1.1.1/tldr_1.1.1_linux_x64.tar.gz"
      sha256 "e58cdff38cd9c0b29cec1e90f013f8554111e4f2de5948198752386b93b28c99"
    end
  end

  def install
    bin.install "tldr"
  end

  test do
    system "#{bin}/tldr -version"
  end
end
